### ISSUE TITLE
Keda Manager takes over existing custom keda installation

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/keda-manager#2]
**Description**
Keda Manager should detect and fail in case custom keda installation (other than managed by kyma's keda-manager) already exists

**Expected result**

Installation should fail.. (Given CRD already exists...)
Keda CR status should reflect the keda installation collision

**Actual result**

Keda operator takes over the custom installation ( for example see annotations on keda namespace ) and uninstalls it upon Keda CR removal

**Steps to reproduce**

1. Deploy custom Keda installation manually i.e using `kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.8.0/keda-2.8.0.yaml`
2. Install Keda via Keda Manager
3. Installation finishes with success
4. Keda operator takes over the custom one ( for example see annotations on keda namespace )
5. uninstall Keda CR
6. Custom Keda Installation disappears

**Comment by kwiatekus** [comment]
@moelsayed Thanks.
Indeed the keda operator will not proceed with installation if custom keda installation is present.
However user will learn about it only from the logs

```
1.6692784509634922e+09	ERROR	setup	keda-manager can't be installed on a cluster with an existing Keda installation, exiting..
main.main
```

This information does not surface to the Keda CR.. and hence Kyma CR is is status `Ready` 

```yaml
- apiVersion: operator.kyma-project.io/v1alpha1
  kind: Kyma
  metadata:
   ...
    name: default-kyma
    namespace: kcp-system
  spec:
    channel: stable
    modules:
    - channel: stable
      name: keda
    sync:
      enabled: false
      moduleCatalog: true
      noModuleCopy: true
      strategy: secret
  status:
    activeChannel: stable
    conditions:
    - lastTransitionTime: "2022-11-24T08:25:54Z"
      message: all modules are in ready state
      observedGeneration: 3
      reason: ModulesAreReady
      status: "True"
      type: Ready
    moduleStatus:
    - generation: 1
      moduleName: keda
      name: default-kyma-keda
      namespace: kcp-system
      state: Ready
      templateInfo:
        channel: stable
        generation: 1
        gvk:
          group: operator.kyma-project.io
          kind: Manifest
          version: v1alpha1
        name: moduletemplate-keda
        namespace: kcp-system
        version: 0.0.4
    state: Ready
```
