### ISSUE TITLE
Sample Keda CR is not generated in module template file

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/keda-manager#44]
**Description**

Generated `template.yaml` does not include sample Keda CR in the `spec.data:` field.
Because of that the keda manager has no Keda to install after enabling keda module in the kyma runtime
 
**Expected result**

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: ModuleTemplate
metadata:
  name: moduletemplate-keda
  namespace: kcp-system
  ...
spec:
  target: remote
  channel: stable
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Keda
    metadata:
      name: keda-sample
    spec:
      logging:
        operator:
          level: "debug"
  descriptor:
    component:
      componentReferences: []
     ```
     
**Actual result**

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: ModuleTemplate
metadata:
  name: moduletemplate-keda
  namespace: kcp-system
  ...
spec:
  target: remote
  channel: stable
  data:

  descriptor:
    component:
      componentReferences: []
     ```

**Steps to reproduce**

run `make module-build`

**Troubleshooting**

Could be that it is caused by our non-flat project structure and is dependant on #43
