### ISSUE TITLE
Keda namespace remains in termination state after Keda Module uninstallation

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/keda-manager#47]
**Description**

Keda namespace is not deleted after keda uninstallation

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    kubernetes.io/metadata.name: keda
  name: keda
spec:
  finalizers:
  - kubernetes
status:
  conditions:
  - lastTransitionTime: "2022-10-31T13:26:04Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the
      complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is
      currently unable to handle the request'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2022-10-31T13:25:57Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2022-10-31T13:26:40Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2022-10-31T13:26:40Z"
    message: All content successfully removed
    reason: ContentRemoved
    status: "False"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2022-10-31T13:25:57Z"
    message: All content-preserving finalizers finished
    reason: ContentHasNoFinalizers
    status: "False"
    type: NamespaceFinalizersRemaining
  phase: Terminating

```

**Expected result**

keda namespace should be deleted

**Actual result**

keda namespace remains in termination state

**Steps to reproduce**

Uninstall Keda form Kyma by editing Kyma CR

**Troubleshooting**
