### ISSUE TITLE
Configurable Istio Sidecar Injection for KEDA Workloads

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/keda-manager#501]
#### Description:
We would like to add support for configuring Istio sidecar injection for both the KEDA operator and API metric server workloads. The configuration should be enabled or disabled through a new boolean attribute in the KEDA custom resource definition (CRD). By default, the attribute should be set to `false`.

#### Acceptance Criteria:
- A new boolean attributes (e.g., `enableIstioSidecarInjection`) is introduced in the KEDA custom resource.
- The default value for this attribute is set to `false`.
- When the attribute is set to `true`, Istio sidecar injection labels are added to the KEDA operator and/or API metric server workloads respectively.

#### Technical Requirements:
- Modify KEDA manager to add support for the new attribute in the custom resource.
- If `enableIstioSidecarInjection: true`, apply the following Istio labels to both KEDA operator and API metric server:
  ```yaml
  sidecar.istio.io/inject: "true"
  ```
- Update the CRD with the new boolean attributes.

#### Testing Strategy:
- Add unit tests to validate that the Istio sidecar injection labels are applied correctly based on the boolean value of the new attribute

#### Notes:
- The default behavior should remain unchanged (no sidecar injection) unless the new attribute is explicitly enabled.

#### Example:
```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Keda
metadata:
  name: default
spec:
  istio:
    operator:
      enableIstioSidecarInjection: true/false
    metricServer:
      enableIstioSidecarInjection: true/false
```
