### ISSUE TITLE
Keda manager installs Keda with overcommited resources

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/keda-manager#521]
**Description**

Default Keda CR defines overcommited resource requests for keda workloads

```
apiVersion: operator.kyma-project.io/v1alpha1
kind: Keda
metadata:
  name: default
spec:
  resources:
    operator:
      requests:
        cpu: "300m"
        memory: "150Mi"
    metricServer:
      requests:
        cpu: "300m"
        memory: "500Mi"
```

Those should be reduced, as keda [documents](https://keda.sh/docs/2.15/operate/cluster/#cluster-capacity) that 100m is enough for production-grade installation

Additionally we should also reduce resources for keda admission webhook.

**Testing strategy**
No new tests added. Existing integration tests should still succeed with reduced requested resources.

**Reasons**

Conservation of cluster compute resources
