### ISSUE TITLE
Enable metrics for Keda controllers and provide the ability to add pod annotations for dynatrace

### ISSUE THREAD

**Issue by linuxbsdfreak** [kyma-project/keda-manager#608]
**Description**

Enable metrics for Keda controllers and provide the ability to add pod annotations for dynatrace

**Reasons**

We would like to monitoring the **ScaledObject** CR metrics for alerting under keda via dynatrace annotations under the keda pods. Please provide the following configuration for the keda module as part of the deployment: 

 - make sure keda template is rendered WITH metric endpoints enabled
```
prometheus:
  metricServer:
    # -- Enable metric server Prometheus metrics expose
    enabled: true
    # -- HTTP port used for exposing metrics server prometheus metrics
    port: 8080
    # -- HTTP port name for exposing metrics server prometheus metrics
    portName: metrics
    # -- App Protocol for service when scraping metrics endpoint
  operator:
    # -- Enable KEDA Operator prometheus metrics expose
    enabled: true
    # -- Port used for exposing KEDA Operator prometheus metrics
    port: 8080
  webhooks:
    # -- Enable KEDA admission webhooks prometheus metrics expose
    enabled: true
    # -- Port used for exposing KEDA admission webhooks prometheus metrics
    port: 8080
    # -- App Protocol for service when scraping metrics endpoint
```
 - Configuration of keda pods annotations should be possible via Keda CR
```
podAnnotations:
  # -- Pod annotations for KEDA operator
  keda:
     metrics.dynatrace.com/scrape: 'true'
     metrics.dynatrace.com/path: '/metrics'
     metrics.dynatrace.com/port: '8080’
     metrics.dynatrace.com/secure: 'false'	
  # -- Pod annotations for KEDA Metrics Adapter
  metricsAdapter:
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: '/metrics'
    metrics.dynatrace.com/port: '8080’
    metrics.dynatrace.com/secure: 'false'
  # -- Pod annotations for KEDA Admission webhooks
  webhooks:
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: '/metrics'
    metrics.dynatrace.com/port: '8080’
    metrics.dynatrace.com/secure: 'false'
```
 - Configuration of keda pods annotations should be possible via details view in busola UI (use dedicated widgets)

We need to be alerted on misconfigured ScaledObject CRs and also create dashboards in Dynatrace using the keda metrics. 

**Attachments**
