### ISSUE TITLE
Expose the used Keda version to the User

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/keda-manager#622]
**Description**

Provide information about installed keda version as part of Keda CR.
Extend the status, so that keda version is included.

```yaml
status:
  conditions:
    - lastTransitionTime: '2025-05-07T07:56:12Z'
      message: keda-operator and keda-operator-metrics-server ready
      reason: Verified
      status: 'True'
      type: Installed
  served: 'True'
  state: Ready
  kedaVersion: 2.17
```

**AC**

 - [x] Keda version is accessible from Keda CR status
 - [x] Keda version is visible on Keda CR details view in kyma dashboard
 - [x] `app.kubernetes.io/version` on keda resources installed by keda-manager (`keda.yaml`) should show keda version, not kyma's keda-module version

**Reasons**

Users of keda module are not aware about the actual Keda version installed by our manager and therefore they do not know which Keda features could be used on their managed kyma clusters.

**Attachments**
