### ISSUE TITLE
Introduce Deletion Strategy Mechanism

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/keda-manager#89]
**Description**

The goal is to conform with k8s deletion mechanism and ensure it's implemented correctly with minimal impact on the module's functionality.

User will effectively remove keda module only if he first manually removes all ScaledObjects created by him.
If he doesn't do it, keda module deletion is initiated but remains blocked. The remaining user created Scaled objects should remain controlled by the keda workloads (they should not be orphaned).
Keda CR status reflects the blocked deletion (this status should also surface to Kyma CR status)
Once User removes all the CRs (Scaled objects), the deletion process will continue and there will be nothing left that belongs to keda module on the cluster.

AC:
- [x] Implement the mechanism for the chosen strategy in the module.
- [x] Update the module's documentation.
- [x] Make sure to reflect the changes in tests

**Reasons**

To minimize any negative impact on the module's functionality and help the team to keep the module in a stable state.
To conform with k8s module lifecycle best practices.
To avoid orphaned objects that may become corrupted when the module is re-introduced

**Comment by kwiatekus** [comment]
When deleting KEDA module from KYMA having active scaled objects object I see an error in the KEDA CR status:
```
  status:
    conditions:
    - lastTransitionTime: "2023-03-06T09:26:54Z"
      message: found 1 items with VersionKind keda.sh/v1alpha1
      reason: DeletionErr
      status: "False"
      type: Installed
    state: Error
```

After deletion of scaled objects:
 - the keda workloads were removed
 - KEDA CR got removed
 - KYMA status resolved to READY
 - keda operator eventually got removed

Everything as expected. Great job!
